from pathlib import Path
import json,csv,hashlib,collections,html,re
p=Path(__file__).resolve().parent;root=p.parents[1];ref=root/'reference/pollen-microduck-rl-develop';parts=[]
for f in sorted((ref/'microduck/assets').glob('*.part')):
 x=json.loads(f.read_text());parts.append({'file':str(f.relative_to(root)),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),**x})
configs=[]
for f in sorted(ref.rglob('config*.json')):
 text=f.read_text(); match=re.search(r'"url"\s*:\s*"([^"]+)"',text)
 x={'url':match.group(1)} if match else {}
 for key in ['outputFormat','simplify_stls','max_stl_size']:
  field=re.search(r'"'+key+r'"\s*:\s*([^,\n]+)',text)
  if field:
   try:x[key]=json.loads(field.group(1))
   except ValueError:pass
 if x.get('url','').startswith('https://cad.onshape.com'):
  configs.append({'path':str(f.relative_to(root)),'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'url':x['url'],'outputFormat':x.get('outputFormat'),'simplify_stls':x.get('simplify_stls'),'max_stl_size':x.get('max_stl_size')})
manifest=json.loads((p/'manifest.json').read_text());pins=json.loads((p/'pinned-sources.json').read_text());tree=json.loads((root/'research/imu-contact-identity-2026-09-08/microduck_rl-tree.json').read_text())
revision_counts=collections.Counter((x['documentMicroversion'],x.get('documentVersion')) for x in parts)
r={'revision':'MD-ORIGINAL-CAD-ACCESS-20260908-A','date':'2026-09-08','outcome':'CANNOT DETERMINE: original BRep/STEP access and production revision identity unconfirmed','acquired_geometry_files':[],'acquired_official_metadata':pins,
 'local_interface':{'bridge':'/Users/leifrydenfalk/dev/ce-workshop/ce-onshape','doctor':'doctor.txt','result':'No configured key pair; .env absent. Checked documented process/.env/ONSHAPE_KEYFILE loader, without displaying secrets. No Onshape callable MCP tool exposed in this session. This is not a machine-wide credential search or proof no signed-in account exists.','existing_capabilities':'ceonshape/api.py has workspace-based partstudio feature/boundingbox/mass/STL and async STEP/IGES/Parasolid translation wrappers plus external-data download. docs/API.md explicitly labels endpoints unverified without credentials. No geometry/write probe run.'},
 'guest_browser':json.loads((p/'guest-browser.json').read_text()),
 'access':{'guest_browser':'Fresh isolated Playwright Chrome redirects to https://cad.onshape.com/signin; title Sign in, visible Continue and sign-up flow. Screenshot captured and viewed. No guest document/export UI exposed. No retries or login attempted.','document_page':'HTTP200 only1542-byte JavaScript bootstrap; not evidence of document geometry or public visibility.','document_api':'HTTP403 resource absent or insufficient permission; cannot distinguish those outcomes.','elements_api':'HTTP403','pinned_parts_api':'HTTP401 Unauthenticated API request','scope':'Anonymous standard GETs only, no authentication bypass, account login, permission change or remote design mutation. No document export entitlement demonstrated.'},
 'document_id':'804927696f06d877f3f1803e','assembly_workspace_id':'5b75db19292e71970de02dee','assembly_element_id':'ef6e972847fec8d82570b35e','roller_assembly_element_id':'ed34b749f5a3718f68024fd5','testbench_workspace_id':'3df6f6a8dcea50fb5658e3c0','testbench_element_id':'54c1186243f1b4db10e4bd59',
 'revision_groups':[{'microversion':a,'named_version_id':b,'part_sidecars':n} for (a,b),n in revision_counts.items()],
 'named_version_urls':[{'url':'https://cad.onshape.com/documents/'+did+'/v/'+vid+'/e/'+eid,'basis':'Derived from existing sidecar documentVersion and elementId, not a configured immutable assembly URL; guest export permission unverified'} for did,vid,eid in sorted({(x['documentId'],x['documentVersion'],x['elementId']) for x in parts if x.get('documentVersion')})],
 'config_url_scope':'All indexed config URLs use mutable w/workspace selectors; none supplies an immutable assembly version URL.',
 'source_correction':'Original SOURCE-COMMIT.txt text claims all43sidecars use2f167ea7efece4caa36b89eb; direct JSON audit finds37 atthat microversion and two older pinned groups of3each. Do not export every part from one current workspace and call it identical to the published simulation. An additive SOURCE-COMMIT.txt correction now links this audit; sidecar and mesh bytes unchanged.',
 'provenance_scope':{'local_git_pin':'29e887ecfbf5d37144759e5a9f8a176dfb83d547','current_research_git_pin':'2b25a48b08f1f17bc38c90bb03144c81fbd9ed07','verified_current_subset':'Six unchanged official source files downloaded and hashed: assembly export config, top head shell, eye ring, jaw_soft, rim and battery locker sidecars. Remaining37sidecars indexed from dated local pinned reference; no blanket remote byte-match claim.','cad_formats_in_pinned_public_tree':[x for x in tree['paths'] if x.lower().endswith(('.step','.stp','.brep','.x_t','.x_b','.iges','.igs'))],'tree_search_limit':'Untruncated microduck_rl Git tree at stated commit, filename extensions only; does not cover private Onshape content, other repositories, release assets or embedded archives.','tessellation':'Config explicitly simplify_stls=true,max_stl_size=1.0. .part sidecars contain identity/configuration metadata, not surfaces or precise dimensions. Existing mesh agreement cannot recover original BRep or establish production hardware fidelity.'},
 'export_route_when_access_is_available':['Use account/document sharing with export permission through existing supported interfaces; no access credential or permission currently demonstrated. Access alone does not establish reuse licence or production identity.','Read source element metadata and configuration, then pin an accessible named version/microversion matching each group before requesting geometry. Preserve the mixed revision inventory; current workspace can drift.','Official Onshape docs support async Part Studio/Assembly STEP and synchronous Parasolid BRep exports. Use external export storeInDocument=false; retain source IDs/configuration, API response, units/export options, SHA256 and unchanged downloaded bytes. Actual supported formats/settings for this document remain unqueried.','Existing bridge start_translation uses w/workspace route; it is not proof of microversion-pinned support. Verify exact endpoint selector against official API before exporting an immutable source. Part IDs containing slash, e.g.J/D, require correct path encoding; do not treat slash as a separator.','Ask document owner for STEP/Parasolid of production head, eye ring, battery support and relevant assemblies with exact version/configuration plus dimensioned original-component drawings if shared API access remains unavailable. Do not treat alpha CAD as confirmed production baseline.'],
 'primary_docs':['https://onshape-public.github.io/docs/api-adv/translation/','https://onshape-public.github.io/docs/auth/apikeys/'], 'parts':parts,'configs':configs,'web_manifest':manifest}
(p/'audit.json').write_text(json.dumps(r,indent=2)+'\n')
fields=['file','name','documentId','documentMicroversion','documentVersion','elementId','partId','configuration','fullConfiguration','sha256']
with (p/'part-identities.csv').open('w',newline='') as f:
 w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(parts)
e=html.escape
body='<h1>Original Microduck CAD access</h1><p>MD-ORIGINAL-CAD-ACCESS-20260908-A · 8 September 2026</p><p><b>No original BRep or STEP acquired. Exact export identities recovered; access remains unconfirmed.</b></p><p>The configured ce-onshape bridge has no credentials. Anonymous document/elements requests return403, pinned parts401. The document page returns an application shell only. A fresh isolated Chrome browser redirects to the Sign in page; screenshot guest-document.png captures the guest result. No document or export UI is exposed. These responses do not establish whether the document is absent or private, and do not establish reuse rights.</p><h2>Exact assembly target</h2><p><a href="'+e('https://cad.onshape.com/documents/'+r['document_id']+'/w/'+r['assembly_workspace_id']+'/e/'+r['assembly_element_id'])+'">Open documented Onshape target</a></p><table><tr><th>Identifier</th><th>Value</th></tr>'
for k in ['document_id','assembly_workspace_id','assembly_element_id','roller_assembly_element_id','testbench_workspace_id','testbench_element_id']:body+='<tr><td>'+e(k.replace('_',' '))+'</td><td><code>'+e(r[k])+'</code></td></tr>'
body+='</table><h2>Three source revisions, not one</h2><table><tr><th>Microversion</th><th>Named version ID</th><th>Sidecars</th></tr>'
for x in r['revision_groups']:body+='<tr><td><code>'+e(x['microversion'])+'</code></td><td>'+e(x['named_version_id'] or 'not recorded')+'</td><td>'+str(x['part_sidecars'])+'</td></tr>'
body+='</table><p>'+e(r['config_url_scope'])+'</p><ul>'+''.join('<li><a href="'+e(x['url'])+'">'+e(x['url'])+'</a> — '+e(x['basis'])+'</li>' for x in r['named_version_urls'])+'</ul><p>'+e(r['source_correction'])+'</p><h2>Head and contact-region part identities</h2><table><tr><th>Part</th><th>Element</th><th>Part ID</th><th>Microversion</th></tr>'
for x in parts:
 if Path(x['file']).name in ['top_head_shell.part','bottom_head_shell.part','face_part.part','noenoeil.part','jaw_soft.part','banana_pcb_locker.part']:
  body+='<tr>'+''.join('<td><code>'+e(x[k])+'</code></td>' for k in ['name','elementId','partId','documentMicroversion'])+'</tr>'
body+='</table><p>All43sidecars and configurations, exact source paths and hashes: audit.json and part-identities.csv. Six representative official files at Git commit2b25a48b08f1f17bc38c90bb03144c81fbd9ed07 were downloaded unchanged and match the older local snapshot. No STEP/BRep-format filename appears in that pinned public repository tree; scope exclusions are explicit in audit.json.</p><p>The simulation export enables STL simplification. Sidecars carry IDs, not BRep or manufacturing dimensions. An alpha mesh or alpha CAD export is not a confirmed production specimen.</p><h2>Concrete access/export route</h2><ol>'+''.join('<li>'+e(x)+'</li>' for x in r['export_route_when_access_is_available'])+'</ol><h2>Existing tooling and sources</h2><p>'+e(r['local_interface']['existing_capabilities'])+'</p><ul>'+''.join('<li><a href="'+e(u)+'">'+e(u)+'</a></li>' for u in r['primary_docs'])+'</ul><p>No shelf edits, purchases, contact, login, remote design changes or credentials exposed. All probes and downloaded metadata retained with hashes.</p>'
for a,b in [('return403','return 403'),('parts401','parts 401'),('all43','all 43'),('All43','All 43'),('use2f167','use 2f167'),('finds37','finds 37'),('atthat','at that'),('of3each','of 3 each'),('commit2b25','commit 2b25'),('e.g.J/D','e.g. J/D')]:body=body.replace(a,b)
(p/'REPORT.html').write_text('<!doctype html><meta charset="utf-8"><title>Microduck original CAD access</title><link rel="stylesheet" href="../../tools/doc.css"><style>body{font:16px system-ui;line-height:1.5;max-width:1150px;margin:35px auto;padding:20px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border:1px solid #ddd;text-align:left}code{overflow-wrap:anywhere}</style>'+body)
assert len(parts)==43 and sorted(revision_counts.values())==[3,3,37]
assert all(x['matches_local'] for x in pins)
for x in manifest+pins:
 if 'file' in x:assert hashlib.sha256((p/x['file']).read_bytes()).hexdigest()==x['sha256']
assert tree['truncated'] is False
print('PASS43identities,37/3/3revision groups,6currentbyte-matches,12capturehashes;noCADexport')
