"""mech.py — GENERATED by cecad.meshshelve. Numbers with sources."""


def mech():
    return {"slug": 'microduck-sole-left', "material": 'TPU',
            "body_mass_g": {"value": 30.025, "source": "MJCF inertial mass of body 'ankle_left' (the WHOLE body, not this mesh alone)"}}
