from pathlib import Path
import json,hashlib,math,html
p=Path(__file__).resolve().parent;root=p.parents[1];m=json.loads((p/'manifest.json').read_text());urls={x['id']:x['url'] for x in m}
local=['spec/sourcing.json','docs/BOM.md','ce-parts/microduck-tof-module/component.json','ce-parts/microduck-tof-module/electrical.part.json','ce-parts/np-f550/component.json','ce-parts/np-f550/docs/np-f550.md','ce-parts/np-f550/docs/deity-np-f550-3350mah-datasheet.pdf','out/open/identity-sourcing.json','out/verify/mech_dims.json']
r={'revision':'MD-TOF-POWER-20260908-A','date':'2026-09-08','status':'Research only. Original module, pack and charger identities unconfirmed. No purchase, contact, operation or physical changes.',
'contract':{'tof':'Pinned Pollen runtime supports both L5CX and L8CX; majority L5 per source comment, not per-unit identity. Four-pin J5: GND, 3V3, SDA, SCL. 0x29 is 7-bit; 0x52 is the shifted 8-bit address in supplier tables. Local ToF site is a pose, not a measured module envelope. No module mounting/clearance PASS possible from it.','battery':'Reference np_f970 mesh is 38.6 x 20.6 x 70.8 mm. Product calls pack removable NP-F550, 2600 mAh. Similar outer dimensions do not establish contact geometry, latch, polarity, current rating or original identity. Runtime 6.6/8.2 V mapping is an indication algorithm, not pack protection or charger cutoff specification.','charger':'docs/BOM.md B5 requires one dual charger; spec/sourcing.json folds charger share into B4 with no separate B5. Whether one charger per robot or shared charging is intended must be explicit.'},
 'tof':[
 {'code':'Pololu 3419','url':urls['pololu'],'status':'Conditional integration candidate, not original or direct STEMMA replacement','body_mm':[13,23,3],'interface':'2.54 mm headers, no Qwiic socket; regulators and level shifters, VIN 3.2–5.5 V. Default SPI requires board configuration for I2C. Manufacturer flags bus load sensitivity. Mounting/optical window fit unknown.','current':'Manufacturer 100 mA typical / 150 mA peak, configuration dependent.','prices_usd_1_100_1000':[24.95,19.43,19.43],'price_scope':'1000 extension uses published 100+ tier; not a volume quote or supply commitment.','stock':366,'stock_source':urls['pololu-supply'],'stock_scope':'Supply page dated 8 September 2026: 366 finished, components for at least 100 more within a few days. 1000 not covered.','second_route':'Manufacturer lists RobotShop as distributor carrying 3419: https://www.pololu.com/distributors/0J61 ; no current reseller price or availability verified.'},
 {'code':'SparkFun SEN-19013 /19013','url':urls['sparkfun'],'status':'Conditional L5 carrier; original unknown, lifecycle conflict between manufacturer and distributor','body_mm':[25.4,12.7,None],'hole_pitch_mm':20.32,'geometry_source':urls['sparkfun-dimensions'],'interface':'Two vertical Qwiic sockets. Schematic v10 dated 2022-01-25: 3V3 directly to AVDD/IOVDD; no regulator or level shifter; R4/R5=2.2k pull-ups. Pin 1 GND, 2 VCC, 3 SDA, 4 SCL. Suitable voltage architecture for L5, not evidence of L8 interchangeability. Board height/socket clearance unknown.','schematic_source':urls['sparkfun-schematic'],'prices_usd_1_100_1000':[25.95,22.06,22.06],'price_scope':'1000 extension of 100+ tier, larger-volume quote requested by supplier; numeric stock not verified.','second_route':urls['sparkfun-digikey'],'second_route_status':'DigiKey 1568-19013-ND currently labels 19013 obsolete/no longer manufactured; no active second supply claim. Direct fetch returned HTTP 403; web product page read.'},
 {'code':'ST VL53L5CX-SATEL','url':urls['st-satel'],'status':'Two breakout boards per package, not one; evaluation-board connector architecture differs from J5','interface':'DB4506 Rev 1: whole board regulator 5-to-3.3 V; two 9-pin connectors. Detachable mini PCB intended for 3.3 V with flying wires. No verified installed fit or direct Qwiic connection.','routes':['https://www.digikey.com/en/products/detail/stmicroelectronics/VL53L5CX-SATEL/14552430','https://estore.st.com/en/products/evaluation-tools/product-evaluation-tools/imaging-evaluation-tools/time-of-flight-evaluation-tools/vl53l5cx-satel.html'],'prices':None,'price_scope':'Existing September 2 DigiKey USD 22.70 is historical only. No refreshed quote; package quantity must be corrected before comparison.'}
 ],
 'battery_charger':[],
 'rating_evidence':[
 {'code':'Duracell DR5','url':urls['duracell'],'facts':'70 × 38 × 20 mm, 99 g, 7.2 V / 2600 mAh / 18.7 Wh. Geometry/capacity reference only; no continuous-current, protection thresholds, contact drawing or current price found.'},
 {'code':'Deity NP-F550','url':urls['deity'],'facts':'7.4 V / 3350 mAh / 24.79 Wh, LG 18650 cells, overcharge and short-circuit protection claimed. Manufacturer PDF explicitly includes low-power-drain non-light NP-F devices. No continuous-discharge rating in captured sheet; do not use capacity/brand as robot-load approval. Different capacity, no original claim. Product page advertises 39 USD; live shop stock not verified.'},
 {'code':'Kinefinity GripBAT 2S A941-203-01','url':urls['kinefinity'],'facts':'70 × 38 × 20 mm, 104 g, 7.4 V / 3500 mAh; manufacturer explicitly rates continuous 5 A / 40 W, operating0–40 °C, lists voltage/current/temperature protection. Current page says DISCONTINUED and OUT OF STOCK. Useful rating evidence only, not a sourceable solution or proof 5 A meets robot demand.'}
 ],
 'corrections_for_review':[
 'B4 PASS sourcing verdict is not original identity, continuous-current or contact-fit PASS. Preserve that distinction in rendering.',
 'B4 current unit prices divide indivisible two-pack sets: a single prototype requires a whole 49.90 USD NextBatteries or 49.99 USD Neewer set. One charger per robot requires N sets unless separately sourced, producing 2N packs; ceil(N/2) sets meets pack count but not one-charger-per-robot count.',
 'B9 bare optical LGA packages require a designed PCB/power/interface/optical placement. Moving them to the HAT is a design change, not automatically the correct part at 100 robots or a 1:1 substitute.',
 'B9 ST SATEL set contains two boards. Do not compare package price directly against one carrier. Their header/flying-wire interface is not the existing Qwiic harness.',
 'Generic requirement for regulation/level shifting on every L5 carrier is too broad; SparkFun schematic demonstrates direct 3.3 V L5. Pollen runtime compatibility does not prove identical carrier circuitry.'
 ],
 'rfq_fields':['Original pack/charger/ToF markings, revision photographs and dimensioned drawings; ToF height, mounting, optical axis/window and connector exit','Pack contact/latch drawings and polarity, cell maker/model, rated continuous and pulse current with temperature/time limits, protection trip/recovery thresholds and required certification records','Measured robot load profile required to compare ratings; no conclusion from capacity or aggregate servo count alone','Charger input connector/protocol and adapter inclusion, both-channel current under simultaneous charge, voltage tolerance/termination, temperature/protection limits and exact controller identity','Quote one prototype then 100/1000 robots with explicit battery and charger quantities, stock date, MOQ, lead time, freight/tax to confirmed destination; no commitment'],
 'web_manifest':m,'local_evidence':[{'path':x,'sha256':hashlib.sha256((root/x).read_bytes()).hexdigest()} for x in local]}
for key,code,currency in [('next','KIT-BB-NPF550#3','USD'),('neewer','66600244','USD'),('pollen','Charger Pack / variant 58538260398454','EUR')]:
 d=json.loads((p/(key+'.json')).read_text());price=d['price']/100
 item={'code':code,'url':urls[key].removesuffix('.js'),'set_price':price,'currency':currency,'set_contents':{'batteries':2,'dual_chargers':1},'available_boolean':d['available'],'numeric_stock':None,'scope':'Availability flag is not numeric stock/leadtime. No volume price breaks. Retail extensions exclude unknown freight/tax.','batch_scenarios':[]}
 if key=='next':item['ratings']='Packs 7.2 V / 2600 mAh. EU plug/car adapter included. Pack continuous current, protection thresholds, dimensions/contact drawing and charger electrical limits not published in captured description.'
 if key=='neewer':item['ratings']='Packs 7.4 V / 2600 mAh. USB dual charger+cable, no wall adapter listed. Input 5 V / 2.1 A; output CH1 8.4 V / 0.6 A / 5 W. CH2/simultaneous total not explicit. Broad protection claims, no numeric pack continuous current/trip thresholds/contact drawing.'
 if key=='pollen':item['ratings']='Official product route, not a confirmed original-part drawing: two batteries + dual charger. Pack maker/capacity/current, charger input/output and delivery timing absent from this page. EUR default storefront; no conversion to USD asserted.'
 for n in [1,100,1000]:
  for purpose,sets in [('one_pack_per_robot_shared_chargers',math.ceil(n/2)),('one_charger_per_robot',n)]:item['batch_scenarios'].append({'robots':n,'purpose':purpose,'whole_sets':sets,'packs_received':2*sets,'chargers_received':sets,'retail_extension':round(sets*price,2)})
 r['battery_charger'].append(item)
(p/'audit.json').write_text(json.dumps(r,indent=2,ensure_ascii=False)+'\n')
e=html.escape
body='<h1>Microduck ToF, battery and charger audit</h1><p>MD-TOF-POWER-20260908-A · 8 September 2026</p><p><b>Conditional sourcing only. No original-unit or manufacturing approval.</b></p>'
body+='<h2>Documented target and gaps</h2>'+''.join('<p><b>'+e(k)+':</b> '+e(v)+'</p>' for k,v in r['contract'].items())
body+='<h2>ToF carriers</h2><table><tr><th>Candidate</th><th>Evidence and unresolved interface</th><th>Price and supply</th></tr>'
for x in r['tof']:
 body+='<tr><td><a href="'+e(x['url'])+'">'+e(x['code'])+'</a><p>'+e(x['status'])+'</p></td><td>'+e(x['interface'])+'<p>Dimensions mm: '+e(str(x.get('body_mm','not established here')))+'</p></td><td>'+e(str(x.get('prices_usd_1_100_1000','not refreshed')))+' USD per piece at 1/100/1000 where stated.<p>'+e(x.get('price_scope',''))+'</p><p>'+e(x.get('stock_scope',''))+'</p><p>'+e(x.get('second_route_status',x.get('second_route','')))+'</p></td></tr>'
body+='</table><h2>Battery and charger routes</h2>'
for x in r['battery_charger']:
 body+='<h3><a href="'+e(x['url'])+'">'+e(x['code'])+'</a></h3><p>'+e(x['ratings'])+'</p><p>Two batteries + one charger: '+e(str(x['set_price'])+' '+x['currency'])+'. Availability flag true; quantity and lead time unknown.</p><table><tr><th>Robots</th><th>Requirement</th><th>Whole sets</th><th>Packs / chargers</th><th>Retail extension</th></tr>'
 for b in x['batch_scenarios']:body+='<tr>'+''.join('<td>'+e(str(v))+'</td>' for v in [b['robots'],b['purpose'].replace('_',' '),b['whole_sets'],str(b['packs_received'])+' / '+str(b['chargers_received']),str(b['retail_extension'])+' '+x['currency']])+'</tr>'
 body+='</table>'
body+='<h2>Current and protection evidence</h2>'+''.join('<p><a href="'+e(x['url'])+'">'+e(x['code'])+'</a>: '+e(x['facts'])+'</p>' for x in r['rating_evidence'])
body+='<h2>Source corrections for review</h2><ul>'+''.join('<li>'+e(x)+'</li>' for x in r['corrections_for_review'])+'</ul><h2>Quote questions</h2><ul>'+''.join('<li>'+e(x)+'</li>' for x in r['rfq_fields'])+'</ul><p>No inquiry sent or order placed. B12 and frozen Ming package unchanged. Full source URLs, revisions and hashes: audit.json and manifest.json.</p>'
(p/'REPORT.html').write_text('<!doctype html><meta charset="utf-8"><title>ToF and power sourcing</title><link rel="stylesheet" href="../../tools/doc.css"><style>body{font:16px system-ui;line-height:1.5;max-width:1150px;margin:35px auto;padding:20px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccd3d8;padding:8px;text-align:left;vertical-align:top}a{color:#075c77}</style>'+body)
assert all(hashlib.sha256((p/x['file']).read_bytes()).hexdigest()==x['sha256'] for x in m if 'file' in x)
a=r['battery_charger'][0];assert [x['whole_sets'] for x in a['batch_scenarios']]==[1,1,50,100,500,1000]
assert a['batch_scenarios'][0]['retail_extension']==49.9
assert a['batch_scenarios'][2]['chargers_received']==50
assert all(x['numeric_stock'] is None for x in r['battery_charger'])
print('PASS: source hashes, whole-set quantities1/100/1000, charger coverage, unknown stock retained')
