from pathlib import Path
import hashlib,json,subprocess
D=Path(__file__).resolve().parent;R=D.parent.parent;ws=R.parent.parent
consumer=ws/'ce-cad/cecad/triad.py';text=consumer.read_text();assert 'unresolved_adds' not in text
p=subprocess.run(['python3',str(D/'test_candidate.py')],text=True,capture_output=True);assert p.returncode==0;(D/'test.log').write_text(p.stdout+p.stderr)
data={'status':'CANNOT DETERMINE: staged major-revision candidate, not installed/released','consumer_evidence':{'path':str(consumer),'sha256':hashlib.sha256(consumer.read_bytes()).hexdigest(),'lines':{'884–900':'triad.mate resolves/calls mate and returns output unwrapped; no compatible call','2930–2938':'walk catches mate exceptions and refuses row before placement','3036':'adds = tuple(str(x) for x in (_mate_field(m, "adds") or ()))'},'unresolved_adds_string_present':False,'scope':'Inspected ce-cad/cecad Python modules and project tools have no unresolved_adds consumer; no ecosystem-wide guarantee claimed.'},'behavior':{'mate':'Always raises ValueError with CANNOT DETERMINE and exact 4 tapping-screw/seating/profile/length/minimum requirement; cannot unlock with caller bool or fabricated partref.','nominal_transform':'Separate named helper returns nominal_transform key only, not transform/joint/dof_left/adds. Historical geometry diagnostic; not assembly placement authority. Required hardware 4 explicit.','compatible':'Retains geometric pattern checks; diameter cannot approve metric thread. Any provided depth >3 mm, nonpositive/nonfinite or conflicting 6 mm field FAIL. Missing minimum and exact tapping hardware keeps CD.'},'required_hardware':{'quantity':4,'manufacturer_callout':'M2 Tapping Screw','part_ref':None,'length_mm':None,'profile':None,'pitch_mm':None,'minimum_engagement_mm':None,'maximum_pilot_depth_mm':3},'tests':{'command':'python3 research/xl330-connection-candidate-2026-09-08/test_candidate.py','exit':p.returncode,'count':7,'nominal_transform_cases':32},'integration_required':['Create major servo and connection iterations through established TRIAD workflow; keep current unchanged until integration/reverification. This candidate manifest is intentionally incomplete as a physical joint, not a ready released full schema.','Preserve all 8 historical mesh_pilot interfaces and 52 provisional screw placements; historical snapshots remain immutable.','Update assembly consumers to record explicit mate refusal and outstanding 4 screws rather than swapping nominal_transform for physical mate or interpreting empty adds as no hardware needed.','Review all 66 direct servo endpoints and 18 declared connection acceptors/12 parts in interface review. New connection will refuse 14 current horn mates; that is an explicit unresolved hardware block, not a license to omit joints.','Only a future source-backed compatible tapping-screw identity/seating/minimum/length validation path can enable physical mate. No boolean override.','Reverify actual mechanical center features, exterior, clearances, load/strip torque and original servo identity; local nominal math does not prove those.'],'files':[{'path':str(p.relative_to(D)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(D.rglob('*')) if p.is_file() and '__pycache__' not in str(p) and p.name not in ['review.json','REPORT.html','preview.png']]}
(D/'review.json').write_text(json.dumps(data,indent=2))
h='''<h1>XL330 horn connection candidate</h1><p><strong>NOT READY TO BUILD FROM. Physical mating is refused.</strong> This research candidate withdraws the 6 mm pilot-depth claim and automatic ISO screw additions. It does not change current shelf links or establish original Microduck identity.</p><p><b>Four M2 tapping screws remain required.</b> Exact part, head/profile/pitch/length, seating and minimum engagement remain unknown; manufacturer maximum pilot depth is 3 mm. An empty sourced-additions list does not mean zero hardware demand.</p><h2>Why mate refuses</h2><p>The inspected TRIAD implementation calls mate directly without compatibility validation, consumes <code>adds</code>, and has no <code>unresolved_adds</code> consumer. Returning a successful transform with only an unknown-hardware note could therefore produce a physical joint without its required screws. Candidate <code>mate()</code> raises a specific CANNOT DETERMINE error instead; the existing walk catches that error and refuses the row before placement.</p><p><code>nominal_transform()</code> is a separately named historical-geometry diagnostic. It returns <code>nominal_transform</code>, no physical <code>transform/joint/dof_left/adds</code> contract, and the explicit four-screw requirement. It must not be substituted for physical mate in an assembly.</p><h2>Verification</h2><p>Seven tests pass. Thirty-two nominal frame/pattern transforms exactly match the frozen original implementation: four pattern indices, opposed/aligned faces, two clock values and two offsets. Tests reject physical mate including a claimed hardware-verification override, the old 6 mm depth, conflicting/nonfinite depths, and metric thread approval from diameter. Existing geometric pattern failure and missing-index refusal remain intact.</p><h2>Integration work</h2><ol>'''
for item in data['integration_required']:h+='<li>'+item+'</li>'
h+='</ol><p><a href="review.json">Consumer evidence, test details and candidate hashes</a> · <a href="sources.json">Frozen baseline hashes</a> · <a href="test.log">Regression log</a> · <a href="../xl330-interface-revision-review-2026-09-08/REPORT.html">Exact dependency review</a></p>'
(D/'REPORT.html').write_text('<!doctype html><meta charset="utf-8"><title>XL330 horn candidate</title><link rel="stylesheet" href="../../tools/doc.css"><main>'+h+'</main>');print('7 tests PASS;32 transforms equal; physical mate refuses; current links unchanged')
