# GENERATED by cecad.meshshelve on 2026-09-01 — a LOADER for a published mesh.
"""part:microduck-soft-mouth-top — cad/part.py, the TRIAD build contract.

    def build(doc, params=None) -> Part

WHAT THIS BUILDS. Pollen Robotics' own published geometry for the mesh
`soft_mouth_top` (MJCF sim asset, CC BY-SA-NC 4.0 (pollen-robotics/microduck_rl README)), copied into geometry/ with its
sha256 in evidence/ledger.jsonl. It is loaded through
`cecad.core.Part.from_mesh` at scale 1000.0 (the file is in metres) and
promoted to a solid when the sewn shell closes; when it does not (a decimated
mesh often will not) the part carries the shell and a note says so — never a
silent empty part. Booleans against a mesh part are not reliable
(ce-cad/CLAUDE.md, "An imported mesh may load as 0 solids"); render, place,
measure and print it, do not cut it.

FRAME. The mesh's own frame, unchanged, so the MJCF geom pos/quat in
ce-assemblies/microduck placements.json place it directly.

WHY IT EXISTS (Leif, 2026-09-01): "why not use the reference mesh directly?
... do quickest possible". A parametric rebuild (origin generated, graded
against this mesh by cad-refcheck) may REPLACE this folder's contents in a
later iteration; the slug stays.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GEOMETRY = "geometry/soft_mouth_top.stl"
SCALE = 1000.0
MATERIAL = 'TPU'


def build(doc, params=None):
    if params:
        raise ValueError("microduck-soft-mouth-top takes no build parameters (got %s) — it loads a published mesh" % sorted(params))
    from cecad.core import Part
    path = os.path.join(ROOT, GEOMETRY)
    if not os.path.exists(path):
        raise FileNotFoundError("microduck-soft-mouth-top: %s is missing — the folder cannot build without its geometry" % path)
    p = Part.from_mesh(path, name="microduck-soft-mouth-top", material=MATERIAL, scale=SCALE, tol=0.05)
    for name, at, d in []:
        p.connector(name, at=tuple(at), dir=tuple(d))
    return p
