"""mech.py — GENERATED by cecad.meshshelve. Numbers with sources."""


def mech():
    return {"slug": 'microduck-trunk-shell-right', "material": 'PLA',
            "body_mass_g": {"value": 199.224, "source": "MJCF inertial mass of body 'trunk_base' (the WHOLE body, not this mesh alone)"}}
