# GENERATED by cecad.mjcfseed — edit the generator or placements.json's source, not this file.
"""assembly:microduck — cad/assembly.py, the TRIAD build contract.

    def build(doc, params=None) -> Assembly

PLACEMENT IS LITERAL HERE, BY DESIGN, AND SAYS SO. TRIAD.md wants joined
parts placed by walking joints.json through each connection's mate(). This
assembly is a PORT of a machine that already exists: every transform in
placements.json was MEASURED off Pollen Robotics' own MJCF (body frames
composed with geom frames at zero pose), which is the datum this port is a
port of. That is a source, not a guess. When every connection kind this
machine uses has a mate() on the shelf, the next iteration replaces this
loader with the walk and keeps placements.json as the check the walk must
reproduce.

Parts are resolved through cecad.triad.load — never by path. A part that
does not resolve is REPORTED as a missing bom row, not silently skipped:
the returned assembly carries `missing` in its notes and check() sees it.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def build(doc, params=None):
    import FreeCAD as App
    from cecad.core import Assembly
    import cecad.triad as triad
    with open(os.path.join(ROOT, "placements.json")) as f:
        rows = json.load(f)["record"]["rows"]
    a = Assembly("microduck")
    a.notes = getattr(a, "notes", [])
    cache, missing, fallback = {}, [], []
    for i, r in enumerate(rows):
        ref = r.get("part")
        if not ref:
            missing.append("%s/%s: unmapped mesh" % (r["body"], r["mesh"]))
            continue
        if ref not in cache:
            try:
                cache[ref] = triad.load(doc, ref)
            except Exception as e:  # noqa: BLE001 - reported, never hidden
                cache[ref] = None
                missing.append("%s: %s" % (ref, e))
        part = cache[ref]
        if part is None:
            # FALLBACK, and it is said so: the vendor's published mesh for this
            # placement, loaded directly (Leif, 2026-09-01: "why not use the
            # reference mesh directly?"). The picture stays complete; the note
            # names every placement drawn from the fallback.
            mf = r.get("mesh_file")
            if mf and os.path.exists(mf):
                try:
                    from cecad.core import Part as _Part
                    key = ("mesh", mf)
                    if key not in cache:
                        cache[key] = _Part.from_mesh(mf, name=r["mesh"], scale=1000.0, tol=0.05)
                    part = cache[key]
                    fallback.append("%s <- %s" % (ref, os.path.basename(mf)))
                except Exception as e:  # noqa: BLE001
                    missing.append("%s: mesh fallback failed: %s" % (ref, e))
                    continue
            else:
                continue
        w, x, y, z = r["world_quat_wxyz"]
        rot = App.Rotation(App.Vector(0, 0, 1), 0)
        rot.Q = (x, y, z, w)
        label = "%s/%s#%d" % (r["body"], ref.split(":")[1], i)
        a.add(label, part, at=tuple(r["world_pos_mm"]), rot=rot, joint="clamped")
    a.notes.append("placed %d of %d instances from placements.json; %d from the VENDOR MESH fallback (%s); missing %d: %s"
                   % (len(rows) - len(missing), len(rows), len(fallback), "; ".join(fallback)[:1500], len(missing), "; ".join(missing)[:1500]))
    return a
