"""mech.py — GENERATED by cecad.meshshelve. Numbers with sources."""


def mech():
    return {"slug": 'microduck-soft-mouth-top', "material": 'TPU',
            "body_mass_g": {"value": 188.766, "source": "MJCF inertial mass of body 'jaw_soft' (the WHOLE body, not this mesh alone)"}}
