export const meta = {
  name: 'microduck-simulate',
  description: 'Animate the Microduck in MuJoCo (open-source simulator) with Pollen\'s published policies, our rebuilt meshes swapped in, rendered to video — and verify it',
  phases: [
    { title: 'Simulate', detail: 'MuJoCo + ONNX policy run, our meshes swapped in, video out' },
    { title: 'Verify', detail: 'independent re-run and frame readback' },
  ],
}
const REPO = '/Users/leifrydenfalk/dev/ce-workshop/ce-designs/microduck'
const PY = '/Applications/FreeCAD.app/Contents/Resources/bin/python'
const CTX = `Repo ${REPO} (git; do NOT commit). GOAL.md rung 3. Leif, 2026-09-01: "i want to see it animated ... working using the open source simulator for it. fully simulated". Toolchain already installed into FreeCAD's python ${PY}: mujoco 3.12.0, onnxruntime 1.29.0, imageio + imageio-ffmpeg (ffmpeg binary via imageio_ffmpeg.get_ffmpeg_exe()). numpy 1.26.4. System python3 has none of these — use ${PY} for everything. Machine is loaded (other agents build in FreeCAD): keep MuJoCo runs short and renders at 640x480; never run more than one heavy process at a time.\n\nSources: Pollen's stock model ${REPO}/reference/pollen-microduck-rl/robot_walk.xml (+ scene.xml, joints_properties.xml, sensors.xml, additional.xml, assets/ meshes in metres) — read ${REPO}/reference/pollen-microduck-rl/microduck_rl_README.md and the cloned repo /private/tmp/claude-501/-Users-leifrydenfalk/191ca988-e752-45fb-a6f7-89dde34532e7/scratchpad/microduck/repos/pollen-robotics_microduck_rl (scripts/infer_policy.py is THE reference for the 61-D observation layout [gyro 3 | projected gravity 3 | joint pos 14 | joint vel 14 | last action 14 | command 13], the 14 actions -> position targets with action_scale, the 50 Hz control loop, the STAND/INIT keyframe, and the joint order). Policies (ONNX, normaliser baked in): ${REPO}/reference/pollen-microduck-simulator/../../research/raw/ has notes; the ONNX files are in the simulator clone at /private/tmp/claude-501/-Users-leifrydenfalk/191ca988-e752-45fb-a6f7-89dde34532e7/scratchpad/microduck/repos/microduck-simulator/app/public/policies/ (BEST_alpha_walking.onnx, BEST_alpha_sitstand.onnx, BEST_alpha_stand.onnx, roulade.onnx, ball_kick_*.onnx) — if a file there is a git-lfs pointer (starts with 'version https://git-lfs'), fetch it from https://huggingface.co/spaces/pollen-robotics/microduck-simulator/resolve/main/app/public/policies/<name> with curl -L. The simulator's app/src/game/duck.js and game.js show exactly how the browser feeds the policy (obs assembly, command vector, action smoothing, STAND keyframe injection) — mirror it.\n\nOUR rebuilt parts: ${REPO}/tools/watch-pass.log lists PASSed slugs; each has out/refcheck/<slug or short name>/rN/ours.stl (mm) or ce-parts/<slug>/iterations/v0.0.1/evidence/refcheck/<stamp>/ours.stl; spec/mesh-to-part.json maps mesh name -> slug. Our meshes are in Pollen's mesh frame, so swapping is replacing the mesh file (convert mm -> metres: scale 0.001 via the MJCF <mesh scale=> attribute or by rewriting the STL) with the same name.`
const DONE = { type: 'object', properties: { files: { type: 'array', items: { type: 'string' } }, video_seconds: { type: 'number' }, frames: { type: 'integer' }, swapped_meshes: { type: 'array', items: { type: 'string' } }, policy: { type: 'string' }, walked_m: { type: 'number' }, fell: { type: 'boolean' }, checks: { type: 'array', items: { type: 'string' } }, open: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' } }, required: ['files', 'checks', 'notes'] }
const VERDICT = { type: 'object', properties: { ok: { type: 'boolean' }, measured: { type: 'array', items: { type: 'string' } }, problems: { type: 'array', items: { type: 'string' } } }, required: ['ok', 'measured', 'problems'] }
phase('Simulate')
const sim = await agent(`${CTX}\n\nBUILD THE SIMULATION LANE, as files under ${REPO}/sim/ and outputs under ${REPO}/out/sim/:\n1. sim/run_policy.py — loads a scene (stock robot_walk.xml with a floor, or the swapped variant), the ONNX policy, reproduces infer_policy.py's loop at 50 Hz with a command vector (forward 0.15 m/s for walking), runs N seconds, records qpos/qvel per frame to out/sim/<name>_traj.npz + json summary (walked distance, max joint speed, min trunk height, fell = trunk z < 0.06 or |roll/pitch| > 60 deg, joint range hits vs the MJCF limits, contacts count). Also run BEST_alpha_sitstand.onnx (sit then stand) and BEST_alpha_stand.onnx. Every number in the summary is measured off the simulation.\n2. sim/swap_meshes.py — writes sim/microduck_ours.xml: the stock model with every PASSed part's mesh replaced by OUR ours.stl (scale 0.001), everything else untouched; prints which meshes were swapped and asserts the model compiles and its zero-pose geom bboxes match the stock model within 1.5 mm per swapped mesh (read them off mujoco's mesh data). Run run_policy.py on BOTH models and compare the walk (distance, fell) — the swap must not change the physics materially (collision geoms are the stock ones; say so).\n3. sim/render_video.py — frames from the recorded trajectory: try mujoco.Renderer offscreen first (set MUJOCO_GL=glfw or egl; if no GL context is available on this headless Mac, FALL BACK to cecad.meshview (import from /Users/leifrydenfalk/dev/ce-workshop/ce-cad; render_groups with a z-buffer, bodies placed from qpos via mujoco.mj_kinematics + data.geom_xpos/xmat) at 640x480, ~10 fps, our parts in orange, stock in grey); encode with imageio + the imageio_ffmpeg binary to out/sim/walk.mp4 (>= 5 s), out/sim/sitstand.mp4, and out/sim/walk.gif (<= 8 MB) for the README; write out/sim/report.json + report.md with the measurements, the renderer used, and the swapped mesh list. READ BACK at least three frames as PNG with the Read tool and describe what is visible; refuse a blank video.\n4. sim/README.md — how to run all of it in three commands.\nReturn files, seconds, frames, swapped meshes, walked distance, whether it fell, checks, open items.`, { label: 'simulate', phase: 'Simulate', schema: DONE })
log(`sim: ${sim ? sim.files.length + ' files' : 'FAILED'}`)
phase('Verify')
const v = sim ? await agent(`${CTX}\n\nINDEPENDENTLY VERIFY the simulation lane. Builder report: ${JSON.stringify(sim).slice(0, 5000)}\n\nRe-run sim/run_policy.py on the stock model for 3 s and on the swapped model; compare walked distance and fall flag to the report (within 20%). Check sim/microduck_ours.xml compiles under mujoco and lists the swapped meshes; check the video files exist with ffprobe-equivalent (imageio read: frame count, size, duration) and extract 3 frames at 0/50/100% to PNG and READ them with the Read tool: is the duck visible, upright, moving between frames? Check out/sim/report.json numbers are measured (not typed). Break one thing on purpose (e.g. feed the policy a zeroed observation) and confirm the report would show it. Return ok + problems with file:line.`, { label: 'verify', phase: 'Verify', schema: VERDICT, effort: 'medium' }) : null
return { sim, verify: v }