"""mech.py — GENERATED by cecad.meshshelve. Numbers with sources."""


def mech():
    return {"slug": 'microduck-neck-pitch-bracket', "material": 'PLA',
            "body_mass_g": {"value": 5.72, "source": "MJCF inertial mass of body 'neck_pitch' (the WHOLE body, not this mesh alone)"}}
