"""mech.py — GENERATED by cecad.meshshelve. Numbers with sources."""


def mech():
    return {"slug": 'microduck-neck-plate', "material": 'PLA',
            "body_mass_g": {"value": 36.841, "source": "MJCF inertial mass of body 'neck' (the WHOLE body, not this mesh alone)"}}
