"""mech.py — GENERATED by cecad.meshshelve. Numbers with sources."""


def mech():
    return {"slug": 'microduck-yaw-roll-motion', "material": 'PLA',
            "body_mass_g": {"value": 48.6, "source": "MJCF inertial mass of body 'yaw_roll_motion' (the WHOLE body, not this mesh alone)"}}
