# GENERATED by tools/gen_fastener_verify.py; rerun after changing evidence inputs.
"""TRIAD marked entry point; original fastener identity and endpoint evidence."""
import hashlib
import json
import sys
from pathlib import Path

INPUT_SHA256 = {'ce-assemblies/microduck/current/placements.json': '2631c5acc53b9bb76baa7a4e8783412e509a4b0f3f068bf6202aa29b5adb6d5a', 'ce-assemblies/microduck/current/joints.json': 'ee948ce652d2303a35a757f091047a99b3ab000555e1d01da49ef9715ecd6180', 'ce-assemblies/microduck/current/bom.json': '8c2cf1315d4d62593a40e7e34dd3d256c225ed388e7607165e2e004d5673dba0', 'ce-assemblies/microduck/current/evidence/thread_identity.py': '936695707313b5cc17600d7b4be094dc7874758f1779f283ac7457afa4062638', 'ce-parts/microduck-face-part/current/cad/interfaces.json': 'd51847ed0dceb32ebf0f7b20d30287b3f383c338a9d798035fc6bd84d643d525', 'ce-parts/microduck-foot-left/current/cad/interfaces.json': '5297752018c8f0272f534a32c5f65cfdfe4f6235d9cc4729f773bd33c1bd586c', 'ce-parts/microduck-foot-right/current/cad/interfaces.json': '71aa87b67981a68d90e01b116d65c1b5329fb740c2a40c79b7f4374b4f0cb29e', 'ce-parts/microduck-power-support/current/cad/interfaces.json': 'd40cac8ad638f97861ec577dc9b7d32e1a7c16dbb6857ffecdc7448c130d799c', 'ce-parts/microduck-top-head-shell/current/cad/interfaces.json': '92578c821c1fe47cd1be1ea6bdfefe860425c7dbd98db520a919366700e332f0', 'ce-parts/microduck-trunk-shell-right/current/cad/interfaces.json': 'd70033e867a71c2400a075f93d97e21d6b54a0940907e6ef924a41b857dae6b4', 'ce-parts/xl330-m288-t/current/cad/interfaces.json': 'f446408e9b4eb0670f6658a3c6c84dfb62e836916e1d2e9ff09d5c307976b1cf'}
try:
    root = Path(__file__).resolve().parents[5]
    stale = [name for name, sha in INPUT_SHA256.items() if hashlib.sha256((root/name).read_bytes()).hexdigest() != sha]
    if stale:
        result = {'verdict': 'CANNOT DETERMINE', 'why': 'Evidence inputs changed; regenerate tools/gen_fastener_verify.py', 'stale': stale}
    else:
        assembly = root/'ce-assemblies/microduck/current'
        sys.path.insert(0, str(assembly/'evidence'))
        from thread_identity import verify
        result = verify(*(json.loads((assembly/(name+'.json')).read_text()) for name in ('placements','joints','bom')))
except BaseException as exc:
    result = {'verdict': 'CANNOT DETERMINE', 'why': '%s: %s' % (type(exc).__name__, exc)}
result.update({'$verify': 1, 'slug': 'microduck', 'input_sha256': INPUT_SHA256})
print(json.dumps(result), flush=True)
raise SystemExit({'PASS': 0, 'FAIL': 1, 'CANNOT DETERMINE': 2}[result['verdict']])
