#!/usr/bin/env python3
"""Inventory existing PCB quote inputs without uploading, converting, or approving."""
import argparse,hashlib,html,json,shutil,subprocess,zipfile
from pathlib import Path
ap=argparse.ArgumentParser();ap.add_argument('--out',type=Path,required=True);a=ap.parse_args();root=Path(__file__).resolve().parents[1];out=a.out.resolve();out.mkdir(parents=True,exist_ok=True)
clone=root/'research/fetched/microduck-replica-fanhao375';rev=subprocess.check_output(['git','-C',str(clone),'rev-parse','HEAD'],text=True).strip();dirty=subprocess.check_output(['git','-C',str(clone),'status','--porcelain'],text=True).strip();assert not dirty,'Replica checkout has uncommitted changes; identify them before claiming a pinned source'
groups=[('Official HAT C1','23eab11927f95ceca0dfa35bf182caeb7db39ea0',[root/'reference/pollen-elec-rpi-robot-hat/production'/x for x in ['PCB01186-C1_elec_RPI_Robot_HAT_PCB.zip','ASE01187-C1_elec_RPI_Robot_HAT_BOM.csv','ASE01187-C1_elec_RPI_Robot_HAT_POS.csv']]),('Replica IMU source - no Gerber release',rev,sorted((clone/'hardware/imu_to_dxl').iterdir()))]
rows=[]
for label,revision,files in groups:
 for p in files:
  if not p.is_file():continue
  dest=out/'PCB source files'/label/p.name;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dest)
  role='Engineering source / 工程源文件'
  if label=='Official HAT C1':role='PCB layers and drill archive / PCB制板文件' if p.suffix=='.zip' else ('Assembly component list / 贴片物料表' if '_BOM' in p.name else 'Assembly placement list / 贴片坐标表')
  crc=None;contents=None
  if p.suffix=='.zip':
   with zipfile.ZipFile(p) as z:crc=z.testzip();contents=z.namelist();assert crc is None
  rows.append({'board':label,'role':role,'file':str(dest.relative_to(out)),'source':str(p.relative_to(root)),'revision':revision,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'zip_crc_ok':crc is None if p.suffix=='.zip' else None,'zip_entries':contents})
# Deliberately distinguish our old reconstruction from the replica source above.
for board in ['robot-hat','imu-to-dxl']:
 for p in sorted((root/'electronics'/board/'out/fab').glob('*.zip')):
  rows.append({'board':'Our historical '+board+' reconstruction - blocked','file':None,'source':str(p.relative_to(root)),'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'role':'Do not substitute for official/replica design','revision':subprocess.check_output(['git','-C',str(root),'log','-1','--format=%H','--',str(p.relative_to(root))],text=True).strip() or None})
audit=json.loads((root/'research/hat-pcba-rfq-2026-09-08/audit.json').read_text());record={'scope':'Local file map only. No uploads, orders, quote submission or manufacturing approval.','official_hat_drc':audit['drc'],'replica_imu_revision':rev,'replica_imu_checkout_clean':True,'replica_imu_exported_gerber_archives':[],'replica_imu_status':'README explicitly says unprototyped and physically unverified; checkout contains EDA Pro project, PCB STEP/PDF, schematic PDF, wiring table and outline DXF, but no Gerber ZIP/BOM CSV/CPL CSV.','files':rows};(out/'JLC FILE MAP.json').write_text(json.dumps(record,indent=2,ensure_ascii=False))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><title>Microduck PCB files — review before quotation</title><style>body{font:17px/1.6 system-ui;max-width:1100px;margin:40px auto;color:#193444;padding:20px}table{border-collapse:collapse;width:100%}td,th{padding:12px;border:1px solid #ccd7dd;text-align:left}a{color:#007090}.gate{padding:20px;background:#fff1e9;border-left:6px solid #c84227}code{overflow-wrap:anywhere}</style><a href="START HERE.html">← Cable guide / 返回接线指南</a><h1>PCB files for quotation review<br>PCB报价文件核对</h1><div class="gate"><b>Not ready to order / 暂不可下单</b><p>The official HAT audit reports 40 DRC errors and 9 warnings. The replica IMU is explicitly unprototyped. No file has been uploaded to JLCPCB and no order has been placed. 原版HAT记录40项DRC错误和9项警告；复刻IMU尚未打样。本次没有上传或下单。</p></div><p>For a bare PCB quotation the relevant file is the board's Gerber/drill archive. Component assembly additionally needs the BOM and placement/CPL file from the same revision. The large whole-robot review ZIP is not a PCB fabrication archive. 裸板报价需要对应板卡Gerber及钻孔文件；贴片还需要同版本BOM及坐标文件。整机审查ZIP不是制板文件。</p><h2>Official HAT C1 / 官方HAT C1</h2><p>The three source files below belong together. Resolve the recorded J4 hole-clearance errors (0.020 mm actual versus 0.200 mm configured), installed-board identity and servo voltage issue first. The placement file includes artwork/fiducial rows; the audit identifies them. Do not silently order these as components or treat this inventory as approval. 三份文件属于同一版本；先核对DRC、实物版本、舵机供电及坐标表中的非器件项目。</p><h2>Replica IMU / 第三方复刻IMU</h2><p>The checkout contains an EDA Pro project and drawings, but no exported Gerber archive, assembly BOM CSV or CPL CSV. The README states it has not been prototyped or physically verified. An engineer must review and export a consistent manufacturing set from that project before it can be a quotation upload set. 源码包含嘉立创EDA专业版工程及图纸，但没有已导出的Gerber、贴片BOM或坐标CSV。必须先审查工程并统一导出，不能把另一个IMU工程的ZIP混用。</p><table><tr><th>Board / 板卡</th><th>File and purpose / 文件用途</th><th>Source revision / 来源版本</th></tr>'''
for r in rows:
 link='<a href="'+html.escape(r['file'],quote=True)+'">'+html.escape(Path(r['file']).name)+'</a>' if r['file'] else '<code>'+html.escape(r['source'])+'</code>'
 s+='<tr><td>'+html.escape(r['board'])+'</td><td>'+link+'<br>'+html.escape(r['role'])+'<br>'+str(r['bytes'])+' bytes</td><td><code>'+html.escape(r['revision'] or 'Unrecorded')+'</code></td></tr>'
s+='''</table><h2>Do not mix up the old local reconstructions / 勿混用旧重建版本</h2><p><code>electronics/robot-hat/out/fab/</code> is our historical reconstruction: its own report says 8 FAIL and 3 CANNOT DETERMINE. <code>electronics/imu-to-dxl/out/fab/</code> is a different local IMU: its report says 3 FAIL and 3 CANNOT DETERMINE, including unrouted nets. These archives are inventoried for identification only and are not copied into the proposed upload files. 旧HAT与旧IMU重建都仍有失败项，不能当作官方或第三方复刻版本提交。</p><p>See <a href="JLC FILE MAP.json">exact file hashes and archived DRC evidence / 文件哈希及DRC记录</a>.</p></html>''';(out/'JLC PCB files.html').write_text(s)
print(len(rows),'PCB source files inventoried; no submission')
