#!/usr/bin/env python3
"""gen_connection_readme.py — render every ce-connections README in THIS triad
root from the folder's own connection.json.

    python3 tools/gen_connection_readme.py            render all
    python3 tools/gen_connection_readme.py <slug>     render one

WHY THIS EXISTS. ce-connections/bin/render-readme.py renders the SHARED
workshop shelf and walks its own ROOT only; it cannot reach a design repo's
ce-connections, and a design repo IS a triad root (TRIAD.md). So the 12 folders
under ce-designs/microduck/ce-connections had no generator at all and their
READMEs were hand-maintained — the exact drift a generated document prevents.
`ce-connections/bin/check.py` catches it: "README line 1 names a generator that
exists".

Nothing here is invented. Every line comes out of record.* in connection.json;
a field that is absent produces no section rather than a plausible sentence.
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CONN = os.path.join(ROOT, "ce-connections")
GEN = "tools/gen_connection_readme.py"   # relative to this triad root, the way check.py resolves it
BANNER = ("<!-- GENERATED by %s from this folder's connection.json — "
          "do not hand-edit; rerun the generator. -->\n" % GEN)


def render(slug):
    base = os.path.join(CONN, slug)
    cur = os.path.join(base, "current")
    cj = os.path.join(cur, "connection.json")
    if not os.path.exists(cj):
        cj = os.path.join(base, "connection.json")
    if not os.path.exists(cj):
        return None, "no connection.json"
    r = json.load(open(cj, encoding="utf-8"))["record"]
    L = [BANNER, "# connection:%s\n" % slug, "\n**%s**\n" % r.get("title", slug)]
    j = r.get("joins") or {}
    if j:
        L.append("\n## What it joins\n\n")
        for k in sorted(j):
            L.append("- **%s** — %s\n" % (k, j[k]))
    L.append("\n## Verdict: %s\n\n%s\n" % (r.get("verdict", "CANNOT DETERMINE"),
                                           r.get("why", "")))
    if r.get("standard"):
        L.append("\n## Standard\n\n**%s** — %s\n" % (r["standard"], r.get("standard_why", "")))
    m = r.get("measured")
    if isinstance(m, dict):
        L.append("\n## What is measured\n\n%s\n\n" % m.get("$what", ""))
        for k, v in m.items():
            if k.startswith("$") or k == "reading":
                continue
            L.append("- `%s` = %s\n" % (k, v))
        if m.get("reading"):
            L.append("\n%s\n" % m["reading"])
    if r.get("not_in_this_folder"):
        L.append("\n## Not in this folder\n\n%s\n" % r["not_in_this_folder"])
    if r.get("adds_parts"):
        L.append("\n## What it adds to the BOM\n\n%s\n\n%s\n"
                 % (", ".join("`%s`" % p for p in r["adds_parts"]),
                    r.get("adds_parts_why", "")))
    if r.get("why_not_a_heat_set_insert"):
        L.append("\n## Why not a heat-set insert\n\n%s\n" % r["why_not_a_heat_set_insert"])
    oq = r.get("open_questions") or []
    if oq:
        L.append("\n## Open questions — every one of these is CANNOT DETERMINE\n\n"
                 "| question | what settles it |\n|---|---|\n")
        for q in oq:
            L.append("| %s | %s |\n" % (q.get("q", ""), q.get("settled_by", "")))
    jj = r.get("joint") or {}
    if jj:
        rating = jj.get("rating") or {}
        L.append("\n## The joint\n\n- holds by **%s**, removable: %s, transmits %s\n"
                 % (jj.get("holds_by"), jj.get("removable"),
                    ", ".join(jj.get("transmits") or [])))
        if rating:
            L.append("- rating: %s\n" % ", ".join(
                "%s = %s" % (k, "**MISSING**" if v is None else v) for k, v in rating.items()))
        if jj.get("why"):
            L.append("\n%s\n" % jj["why"])
    L.append("\n## Contracts\n\n"
             "- `cad/mate.py` — `mate(a_iface, b_iface, params)`; run it directly for its self-test\n"
             "- `compat.py` — `compatible(a_iface, b_iface)`; run it directly for its self-test\n"
             "- `cad/fixture.json`, `cad/shelf_cases.json` — what `ce-connections/bin/check.py` exercises\n"
             "- evidence: `evidence/ledger.jsonl`\n")
    txt = "".join(L)
    for p in (os.path.join(cur, "README.md"), os.path.join(base, "README.md")):
        with open(p, "w", encoding="utf-8") as f:
            f.write(txt)
    return len(txt), None


if __name__ == "__main__":
    slugs = sys.argv[1:] or sorted(
        os.path.basename(d) for d in glob.glob(os.path.join(CONN, "*"))
        if os.path.isdir(d) and not os.path.basename(d).startswith("."))
    n = skipped = 0
    for s in slugs:
        size, err = render(s)
        if err:
            skipped += 1
            print("SKIP  %-32s %s" % (s, err))
        else:
            n += 1
            print("wrote %-32s %d bytes" % (s, size))
    print("\n%d README(s) rendered, %d skipped" % (n, skipped))
