#!/usr/bin/env python3
"""Build a bounded, source-pinned comparison; no purchasing or substitution."""
import argparse,hashlib,html,json,subprocess
from pathlib import Path
ap=argparse.ArgumentParser();ap.add_argument('--out',type=Path,required=True);a=ap.parse_args();r=Path(__file__).resolve().parents[1];o=a.out.resolve();o.mkdir(parents=True,exist_ok=True);clone=r/'research/fetched/microduck-replica-fanhao375';revision=subprocess.check_output(['git','-C',str(clone),'rev-parse','HEAD'],text=True).strip()
sources=['README.md','docs/RECREATION-2026-09-08.md','wiring/cables.json','research/official-hat-audit-2026-09-08.json','reference/pollen-microduck-rl/microduck_README.md','reference/pollen-microduck-rl/microduck_rl_README.md','research/original-cad-access-2026-09-08/pinned-sources.json','research/fetched/microduck-replica-fanhao375/README.en.md','research/fetched/microduck-replica-fanhao375/BOM.en.md','research/fetched/microduck-replica-fanhao375/hardware/imu_to_dxl/README.md','research/fetched/microduck-replica-fanhao375/docs/硬件方案逆向.md']
rows=[
('What it is / 是什么','Our engineering reconstruction in ce-cad, combining source meshes with rebuilt parts. Not certified 1:1. / 我们的ce-cad工程重建，混合参考网格与重建零件，未证明1:1。','Independent community reconstruction by fanhao375. Public design/research files do not mean a completed robot. / fanhao375独立复刻研究，公开文件不代表整机完成。','Pollen Robotics commercial robot. Software and some electronics are public; this is not a complete publicly released manufacturing definition. / Pollen商业机器人，软件及部分电子资料公开，但不是完整公开制造定义。'),
('Servos / 舵机','15 × ROBOTIS Dynamixel XL330-M288-T in our current model and parts list. / 当前模型和清单采用15个XL330-M288-T。','Baseline BOM specifies 15 × XL330-M288-T. HD-1910-C001 is a separate Feetech alternative under discussion. / 基线清单为15个XL330；飞特HD-1910-C001是另一路替代方案。','Official runtime README says fifteen servos; public simulation supports the XL330-family inference. Exact fitted motor variant in the reviewed commercial unit remains unconfirmed. / 官方运行时说明15个舵机，公开模型支持XL330系列推断；目标实物具体型号未确认。'),
('Mechanics and fit / 机械与装配','Reconstructed geometry and mesh repairs must retain evidence and new revisions. Assembly, interference and strength coverage are still incomplete. / 重建和网格修复需保留证据及版本；装配、干涉、强度尚未全部验证。','Derived from public simulation meshes/MJCF. Printed shells, legs and feet and some leg screw fit are documented; that is not proof of every interface. / 来自公开仿真网格，已记录部分打印和腿部螺钉试装，并非所有接口验证。','Manufacturer demonstrates working robots. Published simulation geometry does not certify original manufacturing tolerances, fasteners or the exact production revision. / 厂商展示了工作实机；公开仿真几何不代表生产公差、紧固件或具体版本。'),
('Electronics / 电子','Public HAT C1 source is pinned, but our model differs from that board revision. Our historical HAT/IMU reconstructions have unresolved checks. / 公开HAT C1来源已固定，但当前网格板卡版本不同；旧HAT/IMU重建仍有未解决检查项。','Public HAT reference plus a separate self-designed IMU. Its README explicitly says no prototype or physical verification yet. / 参考公开HAT，另自行设计IMU；作者明确说明IMU未打样、未实物验证。','Working electronics exist in the product; public HAT sources alone do not establish the installed HAT, IMU, camera or ToF revision. / 产品有工作电子系统，但公开HAT文件不能确定目标实机所有板卡版本。'),
('Software and control / 软件与控制','ce-cad engineering review/simulation and archived upstream control sources. No completed walking validation on our physical robot. / ce-cad工程审查和仿真，加上上游控制资料；我们的实机尚未完成行走验证。','Studies/reuses upstream control architecture. Alternative servos require motor protocol, calibration and policy validation; source compatibility is not hardware proof. / 研究复用上游架构；换舵机需验证协议、标定和策略。','Official Rust runtime drives fifteen servos at 50 Hz; official RL repository uses MuJoCo/PPO and exports ONNX policies. / 官方Rust运行时以50 Hz控制15个舵机，MuJoCo/PPO训练并导出ONNX策略。'),
('Physical evidence / 实物证据','Review files and software checks are available; they do not establish a mechanically complete, powered and walking replica. / 有审查文件和软件检查，但不代表整机已完成、可通电行走。','Printed-part and limited fit evidence; the pinned sources do not prove a complete walking replica. / 有打印及有限装配证据，所固定资料不能证明整机行走。','Manufacturer videos demonstrate walking and other behaviors. We have not independently tested the exact production unit being compared. / 厂商视频展示行走等动作；我们没有独立测试此处对应的具体出厂实机。'),
('Version control / 版本管理','Project Git history plus immutable numbered reviews and file hashes. A working-tree render is not automatically a frozen release. / Git历史加不可变审查版本和文件哈希；工作区渲染并非自动冻结发布。','Git checkout pinned to '+revision[:12]+'. Older mechanical archive 2549257 is separately retained. / 固定Git提交，旧机械归档2549257另行保留。','Official runtime, RL and HAT repositories have Git histories. Those commits do not identify a physical product serial number or full production BOM. / 官方软件和HAT有Git历史，但提交不等于实物序列号或完整生产BOM。')]
record={'scope':'Comparison of documented evidence, not equivalence certification','replica_commit':revision,'official_hat_commit':'23eab11927f95ceca0dfa35bf182caeb7db39ea0','official_geometry_pin':'2b25a48b08f1f17bc38c90bb03144c81fbd9ed07','current_project_commit':subprocess.check_output(['git','-C',str(r),'rev-parse','HEAD'],text=True).strip(),'sources':[{'path':s,'sha256':hashlib.sha256((r/s).read_bytes()).hexdigest()} for s in sources],'rows':rows};(o/'VERSION COMPARISON.json').write_text(json.dumps(record,indent=2,ensure_ascii=False))
s='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Microduck — three versions compared</title><style>body{font:16px/1.6 system-ui;color:#193444;margin:0;background:#eff3f5}main{max-width:1320px;margin:auto;padding:35px}h1{font-size:36px}table{border-collapse:collapse;width:100%;background:white}th,td{padding:15px;border:1px solid #ccd7dd;text-align:left;vertical-align:top}th{background:#dfeaf0}td:first-child{width:15%;font-weight:600}td{width:28%}.card{padding:24px;background:white;margin:24px 0;border-radius:12px}.key{border-left:6px solid #00869b}a{color:#00708b}code{overflow-wrap:anywhere}@media print{main{padding:0}body{background:white}tr,.card{break-inside:avoid}h2{break-after:avoid}}</style><main><a href="START HERE.html">← Cable guide / 返回线缆指南</a><h1>Which Microduck are we reviewing?<br>我们在比较哪一种Microduck？</h1><div class="card key"><b>Our current version still uses fifteen XL330-M288-T servos.</b><p>No cheaper motor has been substituted. The community replica and the commercial original are separate references; none of these records proves our version is a 1:1 copy.</p><p><b>当前版本仍采用15个XL330-M288-T舵机，没有换成廉价舵机。</b>社区复刻和商业原版是两个不同参考；这些资料不能证明我们的版本是1:1复制。</p></div><table><thead><tr><th>Topic / 项目</th><th>Our ce-cad version / 我们的版本</th><th>Community replica / 社区复刻</th><th>Commercial original / 商业原版</th></tr></thead><tbody>'''
for row in rows:s+='<tr>'+''.join('<td>'+html.escape(c)+'</td>' for c in row)+'</tr>'
s+='''</tbody></table><h2>The cheaper-servo route / 更便宜舵机的路线</h2><div class="card"><p><b>Feetech HD-1910-C001 is a candidate, not a drop-in replacement or a purchase decision.</b> It needs its own reviewed revision. Validate mounting holes, horn/spline and clearances; supply voltage, connectors and pin order; bus protocol and driver; torque-speed behavior, backlash and calibration; and walking-policy compatibility. A fitting outline or similar three-wire cable does not settle these questions.</p><p><b>飞特HD-1910-C001是候选方案，不是已确认可直接替换的器件，也不是采购决定。</b>需要单独审查版本，验证安装孔、舵盘与间隙、供电、接头针序、总线协议和驱动、力矩速度与回差标定，以及行走策略适配。</p><p>The XL330 supply mismatch already identified in our cable guide remains unresolved. Changing brands does not by itself close the electrical or mechanical checks. 当前XL330供电矛盾仍未解决；换品牌本身不等于通过电气和机械验证。</p></div><h2>Evidence and exact versions / 证据与版本</h2><p><a href="VERSION COMPARISON.json">Local source hashes and comparison record / 本地来源哈希与比较记录</a>. The runtime and RL statements are supported by archived official READMEs, whose hashes are recorded; only commits actually recorded in the source manifests are claimed as pins.</p><ul><li><a href="https://github.com/pollen-robotics/microduck">Official runtime / 官方运行时</a> and <a href="https://github.com/pollen-robotics/microduck_rl">official training repository / 官方训练仓库</a>.</li><li><a href="https://github.com/pollen-robotics/elec_RPI_Robot_HAT/tree/23eab11927f95ceca0dfa35bf182caeb7db39ea0">Official HAT pin / 官方HAT固定版本</a>.</li><li>'''
s+='<a href="https://github.com/fanhao375/microduck-replica/tree/'+revision+'">Community replica at '+revision[:12]+' / 社区复刻固定版本</a>.</li></ul><p>Original fitted-servo identity: CANNOT DETERMINE beyond the stated source scope. Prices and component availability are not compared here. 原版实物舵机的具体型号仍待确认；本页不比较价格与库存。</p></main></html>'
(o/'Compare the three versions.html').write_text(s)
