#!/usr/bin/env python3
"""gen_elec_closure.py — ELECTRICAL-CLOSURE.html from out/elec/closure.json.

Nothing is written here that is not in the JSON. The JSON is written by
tools/elec_close.py, which reads Pollen's own board file. Run that first.
"""
import html
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'out/elec/closure.json')
COR = os.path.join(ROOT, 'out/elec/model-corrections.json')
DST = os.path.join(ROOT, 'ELECTRICAL-CLOSURE.html')

E = html.escape

SECTIONS = [
    ('E1', 'The I²C bus, and the one resistor that keeps it working',
     'Every device physically on i2c3, with the address decided by the strap actually fitted — not by a datasheet default.'),
    ('E2', 'Does the Radxa expose what the HAT asks of it',
     'Header pin by header pin, the function the board wants against the function the vendor publishes on that pin.'),
    ('E3', 'Rails, sources, and dangling nets',
     'Where each rail comes from, and whether any net in the design reaches only one pad.'),
    ('E4', 'Is every part inside its own rated supply band',
     'Pin by pin, because a part with a 1.8 V core and 3.3 V I/O is happy on two rails at once. This is where it does not close.'),
    ('E5', 'Does the power budget close, rail by rail',
     'From the pack, through the buck, to the measured peak draw of fifteen servos walking.'),
    ('E6', 'Does every modelled cable land on something that exists',
     'The twenty-three runs in wiring/cables.json against the connectors on the board.'),
    ('E7', 'Is anything unpowered',
     'Every fitted active device, and every device that hangs off the board on a cable.'),
    ('E9', 'Is every electrical thing in the model at all',
     "Leif's standing order is that every physical thing is in the CAD. The BOM is counted off Pollen's MJCF, which carries "
     'visual and collision geometry and nothing else — this is the electrical half of the gap that left it with zero fastener rows.'),
    ('E8', 'Where OUR model is wrong',
     'The framing of this repository is that the real Microduck works. So a check that fails is first a lead about our own record — '
     'and these are the nine places the copper contradicts or settles something we wrote down.'),
]

CLS = {'PASS': 'ok', 'FAIL': 'no', 'CANNOT DETERMINE': 'cd'}


def main():
    d = json.load(open(SRC))
    cor = json.load(open(COR))
    c = d['counts']
    rows = d['rows']

    L = []
    L.append('<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
             '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
             '<title>Does the electrical system close?</title>\n'
             '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:opsz,wght@8..60,400;8..60,600;8..60,700'
             '&family=Source+Sans+3:wght@400;600&family=IBM+Plex+Mono:wght@400;500&display=swap">\n'
             '<link rel="stylesheet" href="tools/doc.css">\n<style>\n'
             '  .v{font-family:var(--mono);font-size:11px;letter-spacing:.06em;font-weight:500;white-space:nowrap}\n'
             '  .v.ok{color:var(--ready)} .v.no{color:var(--no)} .v.cd{color:var(--partial)}\n'
             '  table.chk{width:100%;border-collapse:collapse;font-size:13.5px;margin:10px 0 18px}\n'
             '  table.chk th{text-align:left;font-family:var(--sans);font-size:11px;letter-spacing:.1em;text-transform:uppercase;'
             'color:var(--ink-2);border-bottom:1.5px solid var(--rule);padding:6px 10px 6px 0;vertical-align:bottom}\n'
             '  table.chk td{border-bottom:1px solid var(--hair);padding:9px 10px 9px 0;vertical-align:top}\n'
             '  table.chk td.i{font-weight:600;width:23%}\n'
             '  table.chk td.m{line-height:1.5}\n'
             '  .cite{display:block;margin-top:5px;font-family:var(--mono);font-size:10.5px;color:var(--ink-2);line-height:1.45}\n'
             '  tr.bad td{background:#fdf6f5} tr.cdr td{background:#fdfaf3}\n'
             '  .headline{border-left:4px solid var(--no);padding:14px 0 14px 20px;margin:22px 0;font-size:17px;line-height:1.5}\n'
             '  .headline b{color:var(--no)}\n'
             '  .note{border-left:3px solid var(--accent);padding:6px 0 6px 18px;margin:14px 0;font-size:14.5px;color:var(--ink-2)}\n'
             '</style>\n</head>\n<body>\n<div class="wrap">\n')

    L.append('<header class="top">\n<div class="eyebrow">PROVE 3 · the internals lane</div>\n'
             '<h1>Does the electrical system close?</h1>\n'
             f'<div class="sub">{E(d["what"])}</div>\n'
             '<div class="rev">'
             f'<span>verdict <b>{E(d["verdict"])}</b></span>'
             f'<span>{c["checks_total"]} checks</span>'
             f'<span>generated by {E(d["generated_by"])}</span>'
             '</div>\n</header>\n')

    L.append('<div class="statbar">')
    for label, key in [('PASS', 'checks_PASS'), ('FAIL', 'checks_FAIL'), ('CANNOT DETERMINE', 'checks_CANNOT_DETERMINE'),
                       ('footprints read', 'hat_footprints'), ('nets read', 'hat_nets'),
                       ('i²c collisions', 'i2c3_collisions'), ('dangling nets', 'dangling_nets'),
                       ('unpowered parts', 'unpowered_fitted_devices'),
                       ('records to correct', 'model_corrections')]:
        L.append(f'<div class="stat"><b>{c[key]}</b><span>{label}</span></div>')
    L.append('</div>\n')

    L.append('<div class="headline"><b>The system does not close, and the place it fails is the one that carries all the power.</b> '
             'The fifteen XL330 servos sit on <code>+BATT</code> with nothing between them and the pack: on Pollen’s own board file '
             'the pads <code>J13.2</code>, <code>J14.2</code>, <code>J3.2</code> and <code>J11.2</code> are all <code>+BATT</code>, '
             'and no regulator on the board has <code>+BATT</code> on an output. The pack runs 6.6–8.2 V under load; the servo is '
             'rated 3.7–6.0 V. That is 10.0 % over its maximum when the pack is empty and 36.7 % over when it is full, with '
             '<b>no operating point anywhere in the pack’s range where the actuators are in specification.</b> '
             'Pollen do not fix it — they write <code>Shutdown(63) = 52</code> into every servo at boot, which is the vendor default '
             '53 with bit 0, <i>Input Voltage Error</i>, cleared.</div>\n')

    L.append('<div class="note"><b>What counts as evidence here.</b> ' +
             ' '.join(f'<b>{E(k)}</b>: {E(v)}' for k, v in d['authority'].items()) + '</div>\n')

    L.append('<nav class="toc">' + ''.join(
        f'<a href="#{s}">{s} · {E(t)}</a>' for s, t, _ in SECTIONS) + '</nav>\n')

    for sec, title, lede in SECTIONS:
        rs = [r for r in rows if r['check'] == sec]
        if not rs:
            continue
        n = {'PASS': 0, 'FAIL': 0, 'CANNOT DETERMINE': 0}
        for r in rs:
            n[r['verdict']] += 1
        L.append(f'<section id="{sec}">\n<h2><span class="n">{sec}</span>{E(title)}</h2>\n'
                 f'<p class="lede">{lede} — <b>{len(rs)}</b> checks: {n["PASS"]} PASS, {n["FAIL"]} FAIL, '
                 f'{n["CANNOT DETERMINE"]} CANNOT DETERMINE.</p>\n')
        L.append('<table class="chk"><tr><th>verdict</th><th>check</th><th>what was measured</th></tr>\n')
        for r in rs:
            cls = CLS[r['verdict']]
            tr = 'bad' if r['verdict'] == 'FAIL' else ('cdr' if r['verdict'] == 'CANNOT DETERMINE' else '')
            L.append(f'<tr class="{tr}"><td><span class="v {cls}">{E(r["verdict"])}</span></td>'
                     f'<td class="i">{E(r["item"])}</td>'
                     f'<td class="m">{E(r["measurement"])}<span class="cite">{E(r["cite"])}</span></td></tr>\n')
        L.append('</table>\n</section>\n')

    L.append('<section id="apply"><h2><span class="n">·</span>The work list</h2>\n'
             f'<p class="lede">{E(cor["what"])} <b>{cor["count"]}</b> corrections, '
             f'<b>{cor["contradicts_a_record"]}</b> of which contradict a record outright.</p>\n'
             '<table class="chk"><tr><th>verdict</th><th>file to change</th><th>change</th></tr>\n')
    for m in cor['corrections']:
        cls = CLS[m['verdict']]
        tr = 'bad' if m['verdict'] == 'FAIL' else ('cdr' if m['verdict'] == 'CANNOT DETERMINE' else '')
        L.append(f'<tr class="{tr}"><td><span class="v {cls}">{E(m["verdict"])}</span></td>'
                 f'<td class="i"><code>{E(m["where"])}</code></td>'
                 f'<td class="m"><b>{E(m["item"])}</b><br>{E(m["change"])}'
                 f'<span class="cite">measured: {E(m["now_measured"])}</span></td></tr>\n')
    L.append('</table>\n</section>\n')

    L.append(f'<section><h2><span class="n">·</span>Verdict</h2><p class="lede">{E(d["verdict_why"])}</p></section>\n')
    L.append('</div>\n</body>\n</html>\n')

    open(DST, 'w').write(''.join(L))
    print(DST, len(''.join(L)), 'bytes')


if __name__ == '__main__':
    main()
