"""Apply the reviewed width correction; preserve priced offer observations."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[2]
p=root/'spec/sourcing.json';d=json.loads(p.read_text());b=next(x for x in d['lines'] if x['id']=='B11')
b['mpn']='MR6700 / 6700 / 61700 open (dimensional candidates; original MPN unknown)'
b['mpn_status']='10 x 15 x 3 mm published mesh envelope confirmed; original installed manufacturer, closure and grade unknown'
b['mpn_note']='CORRECTED 2026-09-08: open 6700 / 61700 catalog candidates are 10 x 15 x 3 mm. SMB 6700ZZ and ZEN 61700-2Z are 10 x 15 x 4 mm; ABF lists FAG 61700-2Z-HLC at 4 mm too. The former claim that 61700-2Z is a shielded 3 mm alternative was wrong. Reject these 4 mm variants for the 3 mm reference envelope. Mesh dimensions do not establish the original installed bearing identity. Sources and hashes: research/bearing-sourcing-2026-09-08/audit.json.'
b['rfq_spec']='Deep-groove ball bearing, bore 10.000 mm, OD 15.000 mm, width 3.000 mm. Quote open MR6700 / 6700 / 61700 dimensional candidates with full manufacturer, suffix, clearance, material, lubrication and tolerance data. Original closure/grade remain unknown. Reject 6700ZZ, 61700-2Z and FAG 61700-2Z-HLC 4 mm variants for this envelope; no substitution without actual-unit evidence and engineering review.'
b['alternates'][0]['why_equivalent']='REJECTED for the 3 mm reference envelope: this shielded variant is 4 mm wide. Historical offer retained for provenance only; excluded from priced offers and best-cost selection. Original installed width/closure must be measured before considering any different envelope.'
b['alternates'][0]['price_note']='Historical observation only (2026-09-02): $1.25, backorder 7-10 days; not reverified by the 2026-09-08 width correction.'
b['alternates'] += [
 {'mpn':'61700-2Z / FAG 61700-2Z-HLC (10 x 15 x 4 mm)','why_equivalent':'REJECTED for 3 mm envelope. Corrects the former false 3 mm shielded-alternative claim. ZEN manufacturer table and ABF FAG listing specify 4 mm; no priced substitute added.','vendor':'ZEN manufacturer catalog; FAG distributor corroboration in audit','url':'https://www.zen.biz/thin-section-bearings','price_note':'No quote; dimensional evidence reviewed 2026-09-08.'},
 {'mpn':'6700 open (10 x 15 x 3 mm)','why_equivalent':'Dimensional/type candidate only; original manufacturer, closure, lubricant, clearance and grade unknown. SMB states it is an authorized EZO distributor. Request full offered MPN and configuration.','vendor':'SMB Bearings (UK)','url':'https://www.smbbearings.com/products/thin-section-bearings.html','price_note':'Catalog read 2026-09-08; price, MOQ and stock unknown; RFQ only, excluded from cost selection.'},
 {'mpn':'61700 open (10 x 15 x 3 mm)','why_equivalent':'Dimensional/type candidate only; original identity unconfirmed. C3 clearance and stainless variants are separate configurations, not assumed equivalent.','vendor':'ZEN Bearings manufacturer','url':'https://www.zen.biz/thin-section-bearings','price_note':'Catalog read 2026-09-08; price, MOQ and stock unknown; RFQ only, excluded from cost selection.'}]
b['unknowns'][0]='Original manufacturer, closure, material, clearance, tolerance and lubricant: CANNOT DETERMINE from published mesh. Mesh bore/OD/width are 10 x 15 x 3 mm; actual-unit measurement and markings must settle installed identity. A catalog source match is not proof of the original part.'
p.write_text(json.dumps(d,indent=1,ensure_ascii=False)+'\n')
p=root/'ce-parts/bearing-15x10x3/sourcing.json';s=json.loads(p.read_text());r=s['record'];r['offers'][0]['note']=b['mpn_note'];r['uncertainties'][0]=b['unknowns'][0];r['uncertainties'][2]='6700ZZ / 61700-2Z / FAG 61700-2Z-HLC catalog width is 4 mm: rejected for the 3 mm reference envelope. Earlier 3 mm shielded-alternative assertion corrected 2026-09-08; historical dated prices remain observations, not new offers.';r['conditional_candidates']=b['alternates'][2:];r['rejected_candidates']=b['alternates'][:2];r['identity_status']='Original installed bearing unidentified; PASS sourcing verdict concerns dated priced dimensional candidates only.'
p.write_text(json.dumps(s,indent=2,ensure_ascii=False)+'\n')
